// <auto-generated />
using Filomena.Backend.Orm;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Filomena.Backend.Orm.Migrations
{
    [DbContext(typeof(NpgsqlContext))]
    [Migration("20171221122321_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Filomena.Backend.Orm.ModuleSource", b =>
                {
                    b.Property<string>("Module")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Source")
                        .IsRequired();

                    b.HasKey("Module");

                    b.ToTable("ModuleSources");
                });
#pragma warning restore 612, 618
        }
    }
}
